footprint: [[0.485, 0.300], [0.485, -0.300], [-0.485, -0.300], [-0.485, 0.300]]
footprint_padding: 0.05
transform_tolerance: 0.3
map_type: costmap

obstacle_layer:
  enabled: true
  obstacle_range: 3.0
  raytrace_range: 4.0
  track_unknown_space: true
  combination_method: 1
  observation_sources: lidar_points laser_scan
  lidar_points:
    data_type: PointCloud2
    topic: /lidar/points
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 1.80
  laser_scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    min_obstacle_height: 0.02
    max_obstacle_height: 1.00

inflation_layer:
  enabled: true
  inflation_radius: 0.45
  cost_scaling_factor: 4.0

static_layer:
  enabled: true
  map_topic: /map
  subscribe_to_updates: true
