immutable: true
direction: outbound
navigation_manifest:
  path: ../../wheelchair_navigation/config/hanyang_routes.yaml
  sha256: 3861e21a6360fe7e32f833f867acb7dd50dccbf45a67f17d93699cea9cbe13c6
route_safety_config:
  path: ../../wheelchair_route_safety/config/route_safety_sim.yaml
  sha256: 6c9496802956c09ec5eb0cb8a02baf417ea426ce10a6409c33bd9532869a79c9
